# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  uds-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: uds-mysql
    volumes:
      - uds-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=uds
      - MYSQL_DATABASE=uds
      - MYSQL_USER=uds
      - MYSQL_PASSWORD=uds

  # PHP 7.3 + nginx
  app:
    image: ambientum/php:latest-nginx
    container_name: uds-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql